[package]
name = "rust_rpg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-terminal = "*"
bracket-rex = "*"
bracket-random = "*"
specs = {version = "0.19.0", features = ["specs-derive"] }